apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-simulator
  template:
    metadata:
      labels:
        app: streaming-simulator
    spec:
      serviceAccountName: default
      containers:
      - name: simulator
        # Aqui usamos la variable combinada
        image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:${TAG}
        env:
        - name: PROJECT_ID
          value: "${PROJECT_ID}"
        - name: TOPIC_ID
          value: "${TOPIC_ID}"
        - name: BATCH_SIZE
          value: "${BATCH_SIZE}"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
