apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-simulator
  template:
    metadata:
      labels:
        app: streaming-simulator
    spec:
      serviceAccountName: default
      containers:
      - name: simulator
        image: IMAGE_PLACEHOLDER
        env:
        - name: PROJECT_ID
          value: "PROJECT_ID_PLACEHOLDER"
        - name: TOPIC_ID
          value: "noaa-raw"
        - name: BATCH_SIZE
          value: "5000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
